# -*- coding: utf-8 -*-
"""sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13UWL5lx-KVTb4k9TUQC3bKv8qlSzVO-y
"""

import pandas as pd
data=pd.read_csv('/content/advertising.zip')

data.head()

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

X = data[['TV', 'Radio', 'Newspaper']]
y = data['Sales']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("R^2 Score:", r2_score(y_test, y_pred))
print("RMSE:", mean_squared_error(y_test, y_pred))

from sklearn.model_selection import cross_val_score
cross_val_score(model, X, y, cv=5, scoring='r2')

forest = RandomForestRegressor()
forest.fit(X_train, y_train)
importances = forest.feature_importances_
print(dict(zip(X.columns, importances)))